#server:
#  port: 7970
#
#spring:
#  datasource:
#    username: root
#    password: 123
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bbkf01?useUnicode=true&characterEncoding=utf8&useSSL=false
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6379
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#          ddl-auto: update
#
#tx-lcn:
#  manager:
#    port: 8070